USE [master]
GO

/****** Object:  Database [WebDb]    Script Date: 8/25/2020 11:37:18 PM ******/
CREATE DATABASE [WebDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\WebDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WebDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\WebDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WebDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WebDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WebDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WebDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [WebDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WebDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [WebDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [WebDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WebDb] SET  MULTI_USER 
GO

ALTER DATABASE [WebDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WebDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WebDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WebDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WebDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [WebDb] SET  READ_WRITE 
GO


